// <auto-generated />
using System;
using AStarDev.ControlDb;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AStarDev.ControlDb.Migrations
{
    [DbContext(typeof(ControlDbContext))]
    [Migration("20260814083352_InitialCreation")]
    partial class InitialCreation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("AStarDev.ControlDb.Files.DeletionStatusEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FileEntityId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("HardDeletePending")
                        .HasColumnType("INTEGER")
                        .HasColumnName("HardDeletePending_Ticks");

                    b.Property<long?>("SoftDeletePending")
                        .HasColumnType("INTEGER")
                        .HasColumnName("SoftDeletePending_Ticks");

                    b.Property<long?>("SoftDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("SoftDeleted_Ticks");

                    b.HasKey("Id");

                    b.HasIndex("FileEntityId")
                        .IsUnique();

                    b.ToTable("FileDeletionStatus", (string)null);
                });

            modelBuilder.Entity("AStarDev.ControlDb.Files.FileAccessDetailEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long?>("DetailsLastUpdated")
                        .HasColumnType("INTEGER")
                        .HasColumnName("DetailsLastUpdated_Ticks");

                    b.Property<Guid>("FileEntityId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastViewed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("LastViewed_Ticks");

                    b.Property<bool>("MoveRequired")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FileEntityId")
                        .IsUnique();

                    b.ToTable("FileAccessDetails", (string)null);
                });

            modelBuilder.Entity("AStarDev.ControlDb.Files.FileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Handle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasAlternateKey("Path", "Name");

                    b.ToTable("Files", (string)null);
                });

            modelBuilder.Entity("AStarDev.ControlDb.Files.ImageDetailEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FileEntityId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FileEntityId")
                        .IsUnique();

                    b.ToTable("ImageDetails", (string)null);
                });

            modelBuilder.Entity("AStarDev.ControlDb.Files.DeletionStatusEntity", b =>
                {
                    b.HasOne("AStarDev.ControlDb.Files.FileEntity", "FileEntity")
                        .WithOne("DeletionStatus")
                        .HasForeignKey("AStarDev.ControlDb.Files.DeletionStatusEntity", "FileEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FileEntity");
                });

            modelBuilder.Entity("AStarDev.ControlDb.Files.FileAccessDetailEntity", b =>
                {
                    b.HasOne("AStarDev.ControlDb.Files.FileEntity", "FileDetail")
                        .WithOne("FileAccessDetail")
                        .HasForeignKey("AStarDev.ControlDb.Files.FileAccessDetailEntity", "FileEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FileDetail");
                });

            modelBuilder.Entity("AStarDev.ControlDb.Files.ImageDetailEntity", b =>
                {
                    b.HasOne("AStarDev.ControlDb.Files.FileEntity", "FileDetail")
                        .WithOne("ImageDetail")
                        .HasForeignKey("AStarDev.ControlDb.Files.ImageDetailEntity", "FileEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FileDetail");
                });

            modelBuilder.Entity("AStarDev.ControlDb.Files.FileEntity", b =>
                {
                    b.Navigation("DeletionStatus")
                        .IsRequired();

                    b.Navigation("FileAccessDetail")
                        .IsRequired();

                    b.Navigation("ImageDetail");
                });
#pragma warning restore 612, 618
        }
    }
}
