// <auto-generated />
using System;
using AStarDev.ControlDb;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AStarDev.ControlDb.Migrations
{
    [DbContext(typeof(ControlDbContext))]
    partial class ControlDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("AStarDev.ControlDb.Files.DeletionStatusEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FileEntityId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("HardDeletePending")
                        .HasColumnType("INTEGER")
                        .HasColumnName("HardDeletePending_Ticks");

                    b.Property<long?>("SoftDeletePending")
                        .HasColumnType("INTEGER")
                        .HasColumnName("SoftDeletePending_Ticks");

                    b.Property<long?>("SoftDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("SoftDeleted_Ticks");

                    b.HasKey("Id");

                    b.HasIndex("FileEntityId")
                        .IsUnique();

                    b.ToTable("FileDeletionStatus", (string)null);
                });

            modelBuilder.Entity("AStarDev.ControlDb.Files.FileAccessDetailEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long?>("DetailsLastUpdated")
                        .HasColumnType("INTEGER")
                        .HasColumnName("DetailsLastUpdated_Ticks");

                    b.Property<Guid>("FileEntityId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastViewed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("LastViewed_Ticks");

                    b.Property<bool>("MoveRequired")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FileEntityId")
                        .IsUnique();

                    b.ToTable("FileAccessDetails", (string)null);
                });

            modelBuilder.Entity("AStarDev.ControlDb.Files.FileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Handle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasAlternateKey("Path", "Name");

                    b.ToTable("Files", (string)null);
                });

            modelBuilder.Entity("AStarDev.ControlDb.Files.ImageDetailEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FileEntityId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FileEntityId")
                        .IsUnique();

                    b.ToTable("ImageDetails", (string)null);
                });

            modelBuilder.Entity("AStarDev.ControlDb.ScrapeConfiguration.ConnectionStringsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ScrapeConfigurationEntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sqlite")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("ScrapeConfigurationEntityId")
                        .IsUnique();

                    b.ToTable("ConnectionStrings", (string)null);
                });

            modelBuilder.Entity("AStarDev.ControlDb.ScrapeConfiguration.ScrapeConfigurationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ScrapeConfigurations", (string)null);
                });

            modelBuilder.Entity("AStarDev.ControlDb.ScrapeConfiguration.ScrapeDirectoriesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseDirectory")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("BaseDirectoryFamous")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("BaseSaveDirectory")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("RootDirectory")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<Guid>("ScrapeConfigurationEntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubDirectoryName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("ScrapeConfigurationEntityId")
                        .IsUnique();

                    b.ToTable("ScrapeDirectories", (string)null);
                });

            modelBuilder.Entity("AStarDev.ControlDb.ScrapeConfiguration.SearchConfigurationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<int?>("MaxResults")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ScrapeConfigurationEntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SearchTerm")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("ScrapeConfigurationEntityId")
                        .IsUnique();

                    b.ToTable("SearchConfigurations", (string)null);
                });

            modelBuilder.Entity("AStarDev.ControlDb.ScrapeConfiguration.UserConfigurationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<Guid>("ScrapeConfigurationEntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionCookie")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("ScrapeConfigurationEntityId")
                        .IsUnique();

                    b.ToTable("UserConfigurations", (string)null);
                });

            modelBuilder.Entity("AStarDev.ControlDb.Files.DeletionStatusEntity", b =>
                {
                    b.HasOne("AStarDev.ControlDb.Files.FileEntity", null)
                        .WithOne("DeletionStatus")
                        .HasForeignKey("AStarDev.ControlDb.Files.DeletionStatusEntity", "FileEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AStarDev.ControlDb.Files.FileAccessDetailEntity", b =>
                {
                    b.HasOne("AStarDev.ControlDb.Files.FileEntity", null)
                        .WithOne("FileAccessDetail")
                        .HasForeignKey("AStarDev.ControlDb.Files.FileAccessDetailEntity", "FileEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AStarDev.ControlDb.Files.ImageDetailEntity", b =>
                {
                    b.HasOne("AStarDev.ControlDb.Files.FileEntity", null)
                        .WithOne("ImageDetail")
                        .HasForeignKey("AStarDev.ControlDb.Files.ImageDetailEntity", "FileEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AStarDev.ControlDb.ScrapeConfiguration.ConnectionStringsEntity", b =>
                {
                    b.HasOne("AStarDev.ControlDb.ScrapeConfiguration.ScrapeConfigurationEntity", null)
                        .WithOne("ConnectionStrings")
                        .HasForeignKey("AStarDev.ControlDb.ScrapeConfiguration.ConnectionStringsEntity", "ScrapeConfigurationEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AStarDev.ControlDb.ScrapeConfiguration.ScrapeDirectoriesEntity", b =>
                {
                    b.HasOne("AStarDev.ControlDb.ScrapeConfiguration.ScrapeConfigurationEntity", null)
                        .WithOne("ScrapeDirectories")
                        .HasForeignKey("AStarDev.ControlDb.ScrapeConfiguration.ScrapeDirectoriesEntity", "ScrapeConfigurationEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AStarDev.ControlDb.ScrapeConfiguration.SearchConfigurationEntity", b =>
                {
                    b.HasOne("AStarDev.ControlDb.ScrapeConfiguration.ScrapeConfigurationEntity", null)
                        .WithOne("SearchConfiguration")
                        .HasForeignKey("AStarDev.ControlDb.ScrapeConfiguration.SearchConfigurationEntity", "ScrapeConfigurationEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AStarDev.ControlDb.ScrapeConfiguration.UserConfigurationEntity", b =>
                {
                    b.HasOne("AStarDev.ControlDb.ScrapeConfiguration.ScrapeConfigurationEntity", null)
                        .WithOne("UserConfiguration")
                        .HasForeignKey("AStarDev.ControlDb.ScrapeConfiguration.UserConfigurationEntity", "ScrapeConfigurationEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AStarDev.ControlDb.Files.FileEntity", b =>
                {
                    b.Navigation("DeletionStatus")
                        .IsRequired();

                    b.Navigation("FileAccessDetail")
                        .IsRequired();

                    b.Navigation("ImageDetail");
                });

            modelBuilder.Entity("AStarDev.ControlDb.ScrapeConfiguration.ScrapeConfigurationEntity", b =>
                {
                    b.Navigation("ConnectionStrings")
                        .IsRequired();

                    b.Navigation("ScrapeDirectories")
                        .IsRequired();

                    b.Navigation("SearchConfiguration")
                        .IsRequired();

                    b.Navigation("UserConfiguration")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
