<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <Product>AStar Development Clock</Product>
    <ApplicationIcon>Assets\astar.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AStarDev.LoggingOTel" />
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="Avalonia.Fonts.Inter" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="Testably.Abstractions" />
    <PackageReference Include="Velopack" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets/**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="src/**/*.cs" />
    <AvaloniaResource Remove="src/**/*.axaml" />
    <None Remove="src/**" />
    <EmbeddedResource Remove="src/**" />
    <ProjectReference Include="../../../../packages/core/utilities/AStarDev.VelopackPublishingAvalonia/AStarDev.VelopackPublishingAvalonia.csproj" />
    <ProjectReference Include="../../../../packages/core/utilities/AStarDev.VelopackPublishing/AStarDev.VelopackPublishing.csproj" />
    <None Include="appsettings.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
